FROM golang:1.25-alpine AS dev
    WORKDIR /app
    RUN apk add --no-cache gcc musl-dev
    RUN go install github.com/air-verse/air@v1.52.3
    COPY go.mod go.sum* ./
    RUN go mod download
    COPY . .
    ENV CGO_ENABLED=1
    CMD ["air", "-c", ".air.toml"]